services:
  - type: web
    name: pinnacle-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt flask
    startCommand: python server.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
